package com.onetoall.yjt.widget.row.tool;

public enum RowActionEnum {
	MY_POST, MY_FIRST, MY_SECEND, MY_THRID, ACTION_COLLECT_MONEY_ALIPAY, ACTION_COLLECT_MONEY_WINXIN, ACTION_COLLECT_MONEY, ACTION_PAY_CHANNEL, ACTION_ENV_SETTINGS, ACTION_PROFILE_PERSON_MANAGER, ACTION_PROFILE_CALL_PHONE, ACTION_CHANGEPWD, ACTION_CHANGEINFO, ACTION_QRCODE_MANAGER, ACTION_CUSTOMER, checkboxAction
}
